### ISSUE TITLE
description is ignored in node.ovc

### ISSUE THREAD

**Issue by yveskerwyn** [openvcloud/ays_templates#5]
When creating a VM using the node.ovc template you can pass a description, but the description is not used when creating the virtual machine.

When checking the OVC client there is simply no description argument in the `machine_create()`, so we first need to update the OVC client too in order to set a description.

**Comment by yveskerwyn** [comment]
tested and approved

**Comment by yveskerwyn** [comment]
Description seems be saved only in AYS repository, not in MongoDB.

When testing again we found that the description doesn't show up in the **End User** portal, it currently only shows up in the AYS Portal (aka "Cockpit"):

See `description` in `data`:

![1](https://user-images.githubusercontent.com/13795109/34946911-e6b7b13c-fa08-11e7-8380-f87d847ddcaa.jpg)


However no description in **End User** portal:

![2](https://user-images.githubusercontent.com/13795109/34946918-ea299d62-fa08-11e7-8f2f-565d0d354133.jpg)

**Comment by riaandn1** [comment]
This needs to be solved in 9.2.1 please. This is urgent and causing problems with the Artilium testing. We cannot continue until this is resolved.

**Comment by andrewayoub** [comment]
this fix was applied to 9.3.0 and available now on 9.2.1 cac9ee042885112437306db7200adf6aef2a8750
